file_in = raw_input("Enter FileName: ")
f = open(file_in).readlines(  )
r_read = open(file_in).read()
count = len(f)
input = raw_input("Enter what string to search for - ")
print ("Total lines: " + str(count))
occ = r_read.count(input)
print (input.upper() + " Occurences: " + str(occ))
